apiVersion: v1
kind: Pod
metadata:
  name: teste-front-pod
  labels:
    app: teste-front-pod
spec:
  containers:
    - name: teste-front-container
      image: lucasnoman/front-teste:v1
      ports:
        - containerPort: 5173
      envFrom:
        - configMapRef:
            name: teste-front-configmap
